version: '3.1'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my-network
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wp
    volumes:
      - wordpress:/var/www/html/sben-chi_blog/
    env_file:
      - .env
    networks:
      - my-network
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/sben-chi_blog
    networks:
      - my-network
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sben-chi/data
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sben-chi/data

networks:
  my-network:
      driver: bridge
